version: '3'
services:
    logger:
         build: .
         ports: 
             - "8080:8080"
         volumes:
                 - $HOME/app:/var/app
         links: 
             - "logstash:logstash"       
         depends_on: 
             - kibana    
    filebeat:
        build: filebeat/
        container_name: filebeat
        links: 
            - "logstash:logstash"
        volumes: 
            - /var/lib/docker:/var/lib/docker:ro
            - /var/run/docker.sock:/var/run/docker.sock 
            - $HOME/app:/var/app 
              

    logstash:
         build: logstash/
         container_name: logstash
         ports: 
             - "5044:5044"
         volumes:
             - $HOME/app:/var/app    
         links: 
              - "elasticsearch:elasticsearch"
         depends_on: 
             - elasticsearch
  
    elasticsearch:
         image: elasticsearch:6.8.7
         environment:
            - discovery.type=single-node
         volumes:
             - $HOME/app:/usr/share/elasticsearch/data 

         ports: 
             - "9200:9200"   
             - "9300:9300" 
    
    kibana:
         image: kibana:6.8.7
         environment:
            SERVER_NAME: kibana.example.org
            ELASTICSEARCH_URL: http://elasticsearch:9200
         links: 
            - "elasticsearch:elasticsearch"   
         volumes:
                - $HOME/app:/var/app
         ports: 
             - "5601:5601"
         depends_on: 
             - elasticsearch    
        
            